
version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/smartpark}
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - FRONTEND_URL=http://localhost:5000

  # Local MongoDB - only used when MONGODB_URI isn't provided
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    profiles:
      - local-dev

volumes:
  mongodb_data:
